#remote_theme: pmarsceill/just-the-docs
theme: just-the-docs

title: Code @ IDE
description: Some coding foundation for Industrial Design Engineers
baseurl: "/code"
url: "https://datacentric.github.io"

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html